### PR TITLE
master: Add linux support to setup.py

### PR DESCRIPTION
**Pull request by leamas**
This PR is the underpinnings in master for #170 and #172. Basically, it makes mkchromecast to a complete pypi package on the Linux side, installable using pip3 and related tools. This simplifies things for both packagers and users on platforms without a native package.  

If/when this PR is accepted,  #170 and #172 need to be rebased to the new master before being merged, but that is a later issue. Basically, this PR is first part of #172. 

The PR contains untested changes with respect to MacOS builds. So, please verify this before merging!

### CODE REVIEW

**Comment by leamas** [comment]
oops.. this will not work without moving mkchromecast.py to bin/mkchromecast. A patch of same commit as in #173 but rebased to devel is available at https://paste.fedoraproject.org/paste/Y3zjc79vuHoBpaUW3qhhlg (silly github does not support attached patches).

**Comment by muammar** [comment]
I think it was moved:

```
muammar@nuc ~/github/mkchromecast [devel] 
± % ls                                                                                                                                                                                                      !10029
archive  changelog.md     example.py  images   Makefile  mkchromecast    mkchromecast.desktop  notifier   requirements.txt  start_tray.py
bin      CONTRIBUTING.md  fedora      LICENSE  man       mkchromecast.1  nodejs                README.md  setup.py          test.py

```

```
muammar@nuc ~/github/mkchromecast [devel] 
± % ls bin                                                                                                                                                                                                  !10032
audiodevice  mkchromecast  node

```

**Comment by muammar** [comment]
`setup.py` is not working for macOS:

```
muammar@zarathustra ~/github/mkchromecast [devel]
± %  python setup.py build_ext                                                                                                                         !11162
/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'package'
  warnings.warn(msg)
running build_ext
```

I have to look at it in more details.

**Comment by leamas** [comment]
Ouch... although I had a bad feeling not being able to test, this indeed lookks strange. Are you sure the previous commit (with the old setup.py) works, or is it an unrelated  external change in the environment?

**Comment by leamas** [comment]
Wish I could help since it's my mess, but alas... Just an idea: tried *packages: ['Mkchromecast']* instead of *package:* since it seemingly chokes on *package:*?

**Comment by leamas** [comment]
BTW, but most likely unrelated: I forgot to nuke the bad shebang.

**Comment by leamas** [comment]
Glad that you fixed it. Also glad it wasn't me;)  I never touched the Makefile, and *package:* is just not supported by distutils these days: https://docs.python.org/3.6/distutils/apiref.html. 

I have seen some other changes like this breaking things lately.

**Pull request merged**
