### PR TITLE
adding audio to screencasting and ubuntu LTS support

### PR DESCRIPTION
**Pull request by edulix**
I've done three changes to adapt mkchromecast to my needs:
- Modified how pyqt is used to accomodate pyqt 5.5, which is what comes in Ubuntu 17.04 LTS
- Removed the -max_muxing_queue_size ffmpeg flag because it's not supported in ffmpeg 2.8.11 (the one I have in Ubuntu 17.04 LTS)
- Most importantly, added initial hacky support for screencasting with audio (pulseaudio) in Linux

Regarding this last point of audio&video, I remark it's been done in a hacky way because I'm asuming it's always done with pulseaudio and Linux. But just doing what @muammar suggested in https://github.com/muammar/mkchromecast/issues/104#issuecomment-357790035 didn't work for me because I wanted a monitor sink to be created. 

Anyway, this is just my way of sharing something that works, I don't expect this to be merged as-is.

### CODE REVIEW

**Comment by mettacrawler** [comment]
@edulix Ubuntu 17.04 is not an LTS, 
https://en.wikipedia.org/wiki/Ubuntu_version_history

**Comment by pandasauce** [comment]
That must be a typo, because actual commit messages say 16.04 which is the latest LTS.

**Comment by pandasauce** [comment]
Tested against 0.3.8.1. With a manual change to the command to pick up the right `DISPLAY` as `:1` instead of `:0.0+0.0` this works. Thanks!

**Comment by muammar** [comment]
@pandasauce I would be glad to merge it. However, it has to be changed to be done in `devel` instead. @edulix would you like to make your changes work with `devel` instead of `master`?  I am sorry to be so slow in replying to it. I would like thank you all  for helping to improve this tool :)

**Comment by edulix** [comment]
Yes I'm actually using 16.04.03 which is the latest LTS. I'm afraid I'm not having time right now to make the changes work on devel, but anyone please feel free to port it. I also want to emphasize that the code I added assumes the usage of pulseaudio.

**Comment by ghomem** [comment]
16.04 LTS and audio support is wonderful! Thanks everyone for this effort.

Are there plans to do an official .deb release with these improvements?

Thanks in advance

**Pull request merged**
